language: node_js

node_js:
  - stable

script:
  - source ./deploy.sh

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME
  region: $AWS_DEFAULT_REGION
  skip_cleanup: true
  local_dir: build
